### PR TITLE
Add minio for local development

### PR DESCRIPTION
**Pull request by sarayourfriend**

### CODE REVIEW

**Comment by sarayourfriend** [comment]
So far this works except that the bucket isn't being created. For some reason the environment variables aren't being handed to `createbucket`, even adding `printenv` to the `createbucket` entrypoint yields nothing. Not sure what could cause this.

**Comment by sarayourfriend** [comment]
Why is this happening in the CI?

```
The MINIO_ROOT_PASSWORD variable is not set. Defaulting to a blank string.
The AWS_STORAGE_BUCKET_NAME variable is not set. Defaulting to a blank string.
```

These variables are defined in the `.envs` files 🤔

**Comment by AetherUnbound** [comment]
This.... Looks right 🤨

**Comment by AetherUnbound** [comment]
Note for posterity: we've moved to a `.env` file because:
1. It's simpler than 3 files
2. It can be read by both the docker-compose file and the individual services

**Review by AetherUnbound — APPROVED** [review]
:tada: :rocket: :woman_singer:

**Pull request merged**
